import {
    type Volunteer,
    type Organization,
    type Campaign,
    type Application,
    type BarangayRiskData, type User
} from "./interfaces.ts";
export const mockAdmin: User[] = [{
    id: 3,
    email: "admin@nutrimap.com",
}]
// -------------------- Volunteers --------------------
export const mockVolunteers: Volunteer[] = [
    {
        id: 1,
        created_at: "",
        email: "test.volunteer@example.com",
        f_name: "Test",
        l_name: "Volunteer",
    },
    {
        id: 2,
        created_at: "",
        email: "john.doe@example.com",
        f_name: "John",
        l_name: "Doe",
    },
    {
        id: 3,
        created_at: "",
        email: "jane.smith@example.com",
        f_name: "Jane",
        l_name: "Smith",
    },
    {
        id: 4,
        created_at: "",
        email: "mark.tan@example.com",
        f_name: "Mark",
        l_name: "Tan",
    },
];

// -------------------- Organizations --------------------
export const mockOrganizations: Organization[] = [
    {
        id: 1,
        created_at: "",
        email: "contact@foodbank.org",
        name: "Test Food Bank",
        organization_name: "Test Food Bank",
        address: "123 Test Street, Test City, Philippines",
        type: 1,
        contact_person: "",
        contact_person_info: "",
    },
    {
        id: 2,
        created_at: "",
        email: "greenearth@example.org",
        name: "Green Earth Foundation",
        organization_name: "Green Earth Foundation",
        address: "123 Eco Street, Makati City, Philippines",
        type: 1,
        contact_person: "",
        contact_person_info: "",
    },
    {
        id: 3,
        created_at: "",
        email: "helpinghands@example.org",
        name: "Helping Hands PH",
        organization_name: "Helping Hands PH",
        address: "45 Bayanihan Ave, Quezon City, Philippines",
        type: 1,
        contact_person: "",
        contact_person_info: "",
    },
    {
        id: 4,
        created_at: "",
        email: "animalcare@example.org",
        name: "Animal Care Society",
        organization_name: "Animal Care Society",
        address: "78 Paw Street, Cebu City, Philippines",
        type: 1,
        contact_person: "",
        contact_person_info: "",
    },
];

// -------------------- Campaigns --------------------
export const mockCampaigns: Campaign[] = [
    {
        id: 1,
        created_at: "",
        title: "Food Distribution Drive",
        name: "Food Distribution Drive",
        organization_name: "Test Food Bank",
        organization_id: 1,
        location: "Test City",
        date: new Date("2025-11-10"),
        description: "A test campaign for food distribution.",
        task: [
            {
                id: 1,
                created_at: "",
                campaign_id: 1,
                task_name: "Food Packing",
                task_description: "Help pack food for distribution.",
                start_date: "2025-11-10",
                volunteer_quota: 10,
                name: "Food Packing",
                description: "Help pack food for distribution.",
                quota: 10,
            },
        ],
    },
    {
        id: 2,
        created_at: "",
        title: "Clean Water Drive",
        name: "Clean Water Drive",
        organization_name: "Green Earth Foundation",
        organization_id: 2,
        location: "Cebu City",
        date: new Date("2025-11-10"),
        description: "A campaign to provide clean water to remote communities.",
        task: [
            {
                id: 2,
                created_at: "",
                campaign_id: 2,
                task_name: "Water Filter Assembly",
                task_description: "Help assemble and test portable water filters.",
                start_date: "2025-11-10",
                volunteer_quota: 10,
                name: "Water Filter Assembly",
                description: "Help assemble and test portable water filters.",
                quota: 10,
            },
            {
                id: 3,
                created_at: "",
                campaign_id: 2,
                task_name: "Community Distribution",
                task_description: "Distribute water filters to designated barangays.",
                start_date: "2025-11-10",
                volunteer_quota: 5,
                name: "Community Distribution",
                description: "Distribute water filters to designated barangays.",
                quota: 5,
            },
        ],
    },
    {
        id: 3,
        created_at: "",
        title: "Tree Planting Marathon",
        name: "Tree Planting Marathon",
        organization_name: "Green Earth Foundation",
        organization_id: 2,
        location: "Davao City",
        date: new Date("2025-12-01"),
        description: "Join volunteers to plant 5,000 trees in deforested areas.",
        task: [
            {
                id: 4,
                created_at: "",
                campaign_id: 3,
                task_name: "Seedling Transport",
                task_description: "Assist in transporting seedlings to planting sites.",
                start_date: "2025-12-01",
                volunteer_quota: 20,
                name: "Seedling Transport",
                description: "Assist in transporting seedlings to planting sites.",
                quota: 20,
            },
            {
                id: 5,
                created_at: "",
                campaign_id: 3,
                task_name: "Planting Crew",
                task_description: "Participate in tree planting and maintenance.",
                start_date: "2025-12-01",
                volunteer_quota: 30,
                name: "Planting Crew",
                description: "Participate in tree planting and maintenance.",
                quota: 30,
            },
        ],
    },
    {
        id: 4,
        created_at: "",
        title: "Food for All",
        name: "Food for All",
        organization_name: "Helping Hands PH",
        organization_id: 3,
        location: "Manila",
        date: new Date("2025-10-30"),
        description: "Feeding program for urban poor families affected by floods.",
        task: [
            {
                id: 6,
                created_at: "",
                campaign_id: 4,
                task_name: "Meal Prep",
                task_description: "Assist in cooking and packing meals.",
                start_date: "2025-10-30",
                volunteer_quota: 15,
                name: "Meal Prep",
                description: "Assist in cooking and packing meals.",
                quota: 15,
            },
            {
                id: 7,
                created_at: "",
                campaign_id: 4,
                task_name: "Distribution Team",
                task_description: "Deliver meals to affected areas.",
                start_date: "2025-10-30",
                volunteer_quota: 10,
                name: "Distribution Team",
                description: "Deliver meals to affected areas.",
                quota: 10,
            },
        ],
    },
    {
        id: 5,
        created_at: "",
        title: "Blood Donation Camp",
        name: "Blood Donation Camp",
        organization_name: "Animal Care Society",
        organization_id: 4,
        location: "Quezon City",
        date: new Date("2025-11-05"),
        description: "Encouraging people to donate blood to save lives.",
        task: [
            {
                id: 8,
                created_at: "",
                campaign_id: 5,
                task_name: "Registration Desk",
                task_description: "Help register donors and guide them through the process.",
                start_date: "2025-11-05",
                volunteer_quota: 25,
                name: "Registration Desk",
                description: "Help register donors and guide them through the process.",
                quota: 25,
            },
        ],
    },
    {
        id: 6,
        created_at: "",
        title: "Education for Every Child",
        name: "Education for Every Child",
        organization_name: "Helping Hands PH",
        organization_id: 3,
        location: "Taguig",
        date: new Date("2025-12-15"),
        description: "Raising funds for school supplies for underprivileged kids.",
        task: [
            {
                id: 9,
                created_at: "",
                campaign_id: 6,
                task_name: "Fundraising Booth",
                task_description: "Assist in manning fundraising booths in malls.",
                start_date: "2025-12-15",
                volunteer_quota: 8,
                name: "Fundraising Booth",
                description: "Assist in manning fundraising booths in malls.",
                quota: 8,
            },
        ],
    },
];
export const mockApplications: Application[] = [
    {
        id: 1,
        created_at: "",
        campaign_task_id: 1,
        volunteer_id: 1,
    },
    {
        id: 2,
        created_at: "",
        campaign_task_id: 2,
        volunteer_id: 2,
    },
    {
        id: 3,
        created_at: "",
        campaign_task_id: 3,
        volunteer_id: 3,
    },
    {
        id: 4,
        created_at: "",
        campaign_task_id: 4,
        volunteer_id: 4,
    },
    {
        id: 5,
        created_at: "",
        campaign_task_id: 5,
        volunteer_id: 3,
    },
    {
        id: 6,
        created_at: "",
        campaign_task_id: 6,
        volunteer_id: 2,
    },
    {
        id: 7,
        created_at: "",
        campaign_task_id: 8,
        volunteer_id: 4,
    },
    {
        id: 8,
        created_at: "",
        campaign_task_id: 9,
        volunteer_id: 2,
    },
];


export const mockBarangayRiskData: BarangayRiskData[] = [
    { id: 71222001, name: 'Bagacay', risk_score: 85, severity: 'HIGH' },
    { id: 71222002, name: 'Batinguel', risk_score: 72, severity: 'MEDIUM' },
    { id: 71222003, name: 'Bunao', risk_score: 65, severity: 'MEDIUM' },
    { id: 71222004, name: 'Cadawinonan', risk_score: 58, severity: 'MEDIUM' },
    { id: 71222005, name: 'Calindagan', risk_score: 45, severity: 'LOW' },
    { id: 71222006, name: 'Camanjac', risk_score: 78, severity: 'HIGH' },
    { id: 71222007, name: 'Candau-ay', risk_score: 62, severity: 'MEDIUM' },
    { id: 71222008, name: 'Cantil-e', risk_score: 55, severity: 'MEDIUM' },
    { id: 71222009, name: 'Daro', risk_score: 88, severity: 'HIGH' },
    { id: 71222010, name: 'Junob', risk_score: 70, severity: 'MEDIUM' },
    { id: 71222011, name: 'Looc', risk_score: 52, severity: 'MEDIUM' },
    { id: 71222012, name: 'Mangnao-Canal', risk_score: 35, severity: 'LOW' },
    { id: 71222013, name: 'Motong', risk_score: 68, severity: 'MEDIUM' },
    { id: 71222014, name: 'Piapi', risk_score: 92, severity: 'HIGH' },
    { id: 71222015, name: 'Poblacion 1', risk_score: 40, severity: 'LOW' },
    { id: 71222016, name: 'Poblacion 2', risk_score: 42, severity: 'LOW' },
    { id: 71222017, name: 'Poblacion 3', risk_score: 38, severity: 'LOW' },
    { id: 71222018, name: 'Poblacion 4', risk_score: 48, severity: 'LOW' },
    { id: 71222019, name: 'Poblacion 5', risk_score: 44, severity: 'LOW' },
    { id: 71222020, name: 'Poblacion 6', risk_score: 50, severity: 'MEDIUM' },
    { id: 71222021, name: 'Poblacion 7', risk_score: 46, severity: 'LOW' },
    { id: 71222022, name: 'Poblacion 8', risk_score: 41, severity: 'LOW' },
    { id: 71222023, name: 'Pulantubig', risk_score: 75, severity: 'HIGH' },
    { id: 71222024, name: 'Tabuc-tubig', risk_score: 60, severity: 'MEDIUM' },
    { id: 71222025, name: 'Taclobo', risk_score: 82, severity: 'HIGH' },
    { id: 71222026, name: 'Talay', risk_score: 67, severity: 'MEDIUM' },
    { id: 71222027, name: 'Bantayan', risk_score: 71, severity: 'MEDIUM' },
    { id: 71222028, name: 'Balugo', risk_score: 54, severity: 'MEDIUM' },
    { id: 71222029, name: 'Banilad', risk_score: 63, severity: 'MEDIUM' },
    { id: 71222030, name: 'Tubtubon', risk_score: 56, severity: 'MEDIUM' },
];

export const mockBarangayRiskData6Months: BarangayRiskData[] = [
    { id: 71222001, name: 'Bagacay', risk_score: 78, severity: 'HIGH' },
    { id: 71222002, name: 'Batinguel', risk_score: 68, severity: 'MEDIUM' },
    { id: 71222003, name: 'Bunao', risk_score: 60, severity: 'MEDIUM' },
    { id: 71222004, name: 'Cadawinonan', risk_score: 55, severity: 'MEDIUM' },
    { id: 71222005, name: 'Calindagan', risk_score: 42, severity: 'LOW' },
    { id: 71222006, name: 'Camanjac', risk_score: 72, severity: 'MEDIUM' },
    { id: 71222007, name: 'Candau-ay', risk_score: 58, severity: 'MEDIUM' },
    { id: 71222008, name: 'Cantil-e', risk_score: 52, severity: 'MEDIUM' },
    { id: 71222009, name: 'Daro', risk_score: 82, severity: 'HIGH' },
    { id: 71222010, name: 'Junob', risk_score: 65, severity: 'MEDIUM' },
    { id: 71222011, name: 'Looc', risk_score: 48, severity: 'LOW' },
    { id: 71222012, name: 'Mangnao-Canal', risk_score: 32, severity: 'LOW' },
    { id: 71222013, name: 'Motong', risk_score: 63, severity: 'MEDIUM' },
    { id: 71222014, name: 'Piapi', risk_score: 86, severity: 'HIGH' },
    { id: 71222015, name: 'Poblacion 1', risk_score: 38, severity: 'LOW' },
    { id: 71222016, name: 'Poblacion 2', risk_score: 39, severity: 'LOW' },
    { id: 71222017, name: 'Poblacion 3', risk_score: 36, severity: 'LOW' },
    { id: 71222018, name: 'Poblacion 4', risk_score: 45, severity: 'LOW' },
    { id: 71222019, name: 'Poblacion 5', risk_score: 41, severity: 'LOW' },
    { id: 71222020, name: 'Poblacion 6', risk_score: 47, severity: 'LOW' },
    { id: 71222021, name: 'Poblacion 7', risk_score: 43, severity: 'LOW' },
    { id: 71222022, name: 'Poblacion 8', risk_score: 39, severity: 'LOW' },
    { id: 71222023, name: 'Pulantubig', risk_score: 70, severity: 'MEDIUM' },
    { id: 71222024, name: 'Tabuc-tubig', risk_score: 56, severity: 'MEDIUM' },
    { id: 71222025, name: 'Taclobo', risk_score: 76, severity: 'HIGH' },
    { id: 71222026, name: 'Talay', risk_score: 63, severity: 'MEDIUM' },
    { id: 71222027, name: 'Bantayan', risk_score: 66, severity: 'MEDIUM' },
    { id: 71222028, name: 'Balugo', risk_score: 51, severity: 'MEDIUM' },
    { id: 71222029, name: 'Banilad', risk_score: 59, severity: 'MEDIUM' },
    { id: 71222030, name: 'Tubtubon', risk_score: 53, severity: 'MEDIUM' },
];

export const mockBarangayRiskData12Months: BarangayRiskData[] = [
    { id: 71222001, name: 'Bagacay', risk_score: 70, severity: 'MEDIUM' },
    { id: 71222002, name: 'Batinguel', risk_score: 62, severity: 'MEDIUM' },
    { id: 71222003, name: 'Bunao', risk_score: 54, severity: 'MEDIUM' },
    { id: 71222004, name: 'Cadawinonan', risk_score: 50, severity: 'MEDIUM' },
    { id: 71222005, name: 'Calindagan', risk_score: 38, severity: 'LOW' },
    { id: 71222006, name: 'Camanjac', risk_score: 65, severity: 'MEDIUM' },
    { id: 71222007, name: 'Candau-ay', risk_score: 53, severity: 'MEDIUM' },
    { id: 71222008, name: 'Cantil-e', risk_score: 48, severity: 'LOW' },
    { id: 71222009, name: 'Daro', risk_score: 75, severity: 'HIGH' },
    { id: 71222010, name: 'Junob', risk_score: 58, severity: 'MEDIUM' },
    { id: 71222011, name: 'Looc', risk_score: 44, severity: 'LOW' },
    { id: 71222012, name: 'Mangnao-Canal', risk_score: 28, severity: 'LOW' },
    { id: 71222013, name: 'Motong', risk_score: 57, severity: 'MEDIUM' },
    { id: 71222014, name: 'Piapi', risk_score: 78, severity: 'HIGH' },
    { id: 71222015, name: 'Poblacion 1', risk_score: 35, severity: 'LOW' },
    { id: 71222016, name: 'Poblacion 2', risk_score: 36, severity: 'LOW' },
    { id: 71222017, name: 'Poblacion 3', risk_score: 33, severity: 'LOW' },
    { id: 71222018, name: 'Poblacion 4', risk_score: 41, severity: 'LOW' },
    { id: 71222019, name: 'Poblacion 5', risk_score: 38, severity: 'LOW' },
    { id: 71222020, name: 'Poblacion 6', risk_score: 43, severity: 'LOW' },
    { id: 71222021, name: 'Poblacion 7', risk_score: 40, severity: 'LOW' },
    { id: 71222022, name: 'Poblacion 8', risk_score: 36, severity: 'LOW' },
    { id: 71222023, name: 'Pulantubig', risk_score: 63, severity: 'MEDIUM' },
    { id: 71222024, name: 'Tabuc-tubig', risk_score: 51, severity: 'MEDIUM' },
    { id: 71222025, name: 'Taclobo', risk_score: 68, severity: 'MEDIUM' },
    { id: 71222026, name: 'Talay', risk_score: 58, severity: 'MEDIUM' },
    { id: 71222027, name: 'Bantayan', risk_score: 60, severity: 'MEDIUM' },
    { id: 71222028, name: 'Balugo', risk_score: 47, severity: 'LOW' },
    { id: 71222029, name: 'Banilad', risk_score: 54, severity: 'MEDIUM' },
    { id: 71222030, name: 'Tubtubon', risk_score: 49, severity: 'LOW' },
];